service: sls-sqs-test
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  stage: play
  region: ap-south-1
  environment:
    SERVICE: sls-sqs-test
    STAGE: play

functions:
  scheduler:
    handler: src/scheduler.default
    role: SchedulerRole
    # events:
    #   - schedule: rate(2 minutes)
  worker:
    handler: src/worker.default
    role: WorkerRole
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - PlayQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    PlayQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: play-queue.fifo
        DelaySeconds: 0
        ContentBasedDeduplication: false
        DeduplicationScope: messageGroup
        MessageRetentionPeriod: 300
        FifoQueue: true
        VisibilityTimeout: 60
    SchedulerRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: sqs-sls-play-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: sqs-sls-play-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "log-group:/aws/lambda/*:*:*"
                - Effect: Allow
                  Action:
                    - sqs:SendMessage
                  Resource:
                    - Fn::GetAtt:
                        - PlayQueue
                        - Arn
    WorkerRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: sqs-sls-play-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: sqs-sls-play-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "log-group:/aws/lambda/*:*:*"
                - Effect: Allow
                  Action:
                    - sqs:ReceiveMessage
                  Resource:
                    - Fn::GetAtt:
                        - PlayQueue
                        - Arn
